# Generated by Django 4.1.6 on 2023-06-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': '同一のユーザー名が既に登録されています'}, max_length=100, unique=True, verbose_name='ユーザー名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('is_admin', models.BooleanField(default=False, verbose_name='管理者')),
                ('is_active', models.BooleanField(default=False, verbose_name='有効')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
