# Generated by Django 4.1.6 on 2023-06-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
