# Generated by Django 4.1.6 on 2023-05-24 02:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=4, verbose_name='ナンバー')),
                ('car_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='車種')),
                ('car_mileage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000000000)], verbose_name='総走行距離')),
                ('remarks', models.TextField(blank=True, max_length=1000, null=True, verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='名前')),
                ('birthday', models.DateTimeField(blank=True, default=None, null=True, verbose_name='生年月日')),
                ('zip_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='郵便番号')),
                ('prefecture', models.CharField(blank=True, max_length=40, null=True, verbose_name='都道府県')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='市区町村番地')),
                ('bldg', models.CharField(blank=True, max_length=50, null=True, verbose_name='建物名')),
                ('tel', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='電話番号はハイフン区切りの数字で入力してください。', regex='^\\d{2,4}-\\d{2,4}-\\d{4}$')], verbose_name='電話番号')),
                ('remarks', models.TextField(blank=True, max_length=1000, null=True, verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100, verbose_name='施設名')),
                ('zip_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='郵便番号')),
                ('prefecture', models.CharField(blank=True, max_length=40, null=True, verbose_name='都道府県')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='市区町村番地')),
                ('bldg', models.CharField(blank=True, max_length=50, null=True, verbose_name='建物名')),
                ('tel', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='電話番号はハイフン区切りの数字で入力してください。', regex='^\\d{2,4}-\\d{2,4}-\\d{4}$')], verbose_name='電話番号')),
                ('remarks', models.TextField(blank=True, max_length=1000, null=True, verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('ride_type', models.CharField(choices=[('迎車', '迎車'), ('賃走', '賃走'), ('回送', '回送')], max_length=10, verbose_name='乗車タイプ')),
                ('start_time', models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='出発時刻')),
                ('arrival_time', models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='到着時刻')),
                ('mileage_from', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000000000)], verbose_name='メーター(前)')),
                ('mileage_to', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000000000)], verbose_name='メーター(後)')),
                ('distance', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000000000)], verbose_name='走行距離')),
                ('fare', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000000000)], verbose_name='料金')),
                ('at_stretcher', models.BooleanField(default=False, verbose_name='ストレッチャー')),
                ('at_night', models.BooleanField(default=False, verbose_name='深夜割増')),
                ('remarks', models.TextField(blank=True, max_length=1000, null=True, verbose_name='備考')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_records', to='myapp.carinformation', verbose_name='搬送車')),
                ('customer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.customerinformation', verbose_name='顧客名')),
                ('place_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlaceFrom', to='myapp.placeinformation', verbose_name='出発地')),
                ('place_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlaceTo', to='myapp.placeinformation', verbose_name='到着地')),
            ],
        ),
    ]
