# Generated by Django 4.1.6 on 2023-06-26 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_salesrecord_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登録者'),
        ),
    ]
