# Generated by Django 4.1.6 on 2023-06-29 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_salesrecord_revised_by_alter_salesrecord_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='mileage_from',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000000000)], verbose_name='MTR(前)'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='mileage_to',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000000000)], verbose_name='MTR(後)'),
        ),
    ]
